# Generated by Django 2.2.6 on 2019-12-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgname', models.CharField(max_length=15)),
                ('image', models.CharField(blank=True, max_length=500)),
                ('name', models.CharField(max_length=25)),
                ('sdesc', models.CharField(max_length=50)),
            ],
        ),
    ]
