# Generated by Django 2.2.6 on 2019-12-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='number',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
