# Generated by Django 2.2.6 on 2019-12-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_carousel_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='state',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
