# Generated by Django 2.2.6 on 2019-12-22 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_carousel_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carousel',
            name='imgname',
        ),
    ]
